### PR TITLE
Forest hardening

### PR DESCRIPTION
**Pull request by tianjuchen**
Calibration for CP-Ti under various temperatures and strain rates levels.

### CODE REVIEW

**Comment by reverendbedford** [comment]
First thing we need to get this current with `dev`.  I'll do that in a minute.

**Comment by reverendbedford** [comment]
Okay @tianjuchen I think some tests will fail and it's your job to fix them.  The first thing to do is eliminate the warnings you get when compiling.  If you want you can change the `CMAKE_BUILD_TYPE` to `Debug` in your cmake configuration.  That will cause the compile to fail on your local machine.  Or you can click "details" next to the failed tests to get the error messages.  Let me know if you need help.

**Comment by tianjuchen** [comment]
@reverendbedford All checks have passed currently with applying initials to 1e-6, but still very sensitivity occasionally 😅.

**Comment by reverendbedford** [comment]
You need to do something like:

```
git fetch -a
git merge dev
git push origin forest_hardening
```

on your local branch to update your branch to dev

**Pull request closed without merging**
