### PR TITLE
Replace boost variant with polymorphic parameters class

### PR DESCRIPTION
**Pull request by dschwen**
Let's see if it actually works... at least it compiles. I guess I should figure out how to run the NEML regression tests locally.

Refs #64

### CODE REVIEW

**Comment by dschwen** [comment]
Oh Lordy! The Python bindings...

**Comment by reverendbedford** [comment]
Yes, I'm a terrible person and test through the python bindings.  But look at all the fun numerical differentiation functions i have setup.

So the idea is you compile with the python bindings and the run "nosetests" to do all the testing.  We try to do both unit testing and regression testing, though the latter was added pretty late.

**Comment by dschwen** [comment]
There still is a weird dynamic linker error related to the python bindings. But if I don't stop now and get us on our camping trip my wife will be angry with me.

**Comment by reverendbedford** [comment]
Have fun.

On mac?  If you send me the error I'll look into it.

**Comment by dschwen** [comment]
Thanks. It isn't seeing the
ParamValue<std::shared_ptr<NEMLObject>>::setFromPY(...) method. But the
implementation is in pyhelp.h

**Comment by dschwen** [comment]
Ok, on my machine the tests run.. and mostly fail. I'll call this a victory increment :-D

Unfortunately the error messaged for the tests are quite terse, and I'm not familiar with properly running these python-wrapped tests in a debugger. Well, it's all a learning experience...

**Comment by dschwen** [comment]
OMG. It's green! I cannot believe it!

**Comment by dschwen** [comment]
Hm, on my machine one of the tests in nosetests now takes a loooong time. I haven't figured out why and which yet.

**Comment by bwspenc** [comment]
@reverendbedford Hopefully this is an acceptable solution. We're happy to revise the code as needed. We can't get rid of this boost dependence soon enough -- I just discovered that we have some new valigrind failures stemming from boost issues.

**Comment by reverendbedford** [comment]
@dschwen @bwspenc  Thanks.  I'll take a look tomorrow, unfortunately I need to finish up some slides tonight.

**Comment by reverendbedford** [comment]
This nicely exposes an issue with me only testing through the bindings: this doesn't compile if you **don't** ask for the python bindings.  (For example, try compiling without -DWRAP_PYTHON=OFF).  The reason is that ParamValue::setFromPY is pure virtual without the definition in pyhelp.h.  And to define it you need all the junk that comes with the pybind11 headers.

I'll try fixing it now, but I don't have any good ideas right now...

**Comment by reverendbedford** [comment]
Hmm, plus the XML parsing tests (tests/test_parse.py) segfault on my machine with g++ 8.3.0.

**Comment by reverendbedford** [comment]
This [branch](https://github.com/Argonne-National-Laboratory/neml/tree/novariant) has the simplest possible solution.  What compilers do you all aim to support?  Looks like gcc 7+ has std::variant.  I guess I'm okay with requiring c++17.

**Comment by dschwen** [comment]
C++17 is out of the question for the MOOSE codebase (even though I'd love to go there). I can look at fixing the broken scenarios. Those should get added to the CI!

**Comment by dschwen** [comment]
Writing a small neml::variant class should be quite trivial, but I would
not advocate that design.

**Comment by reverendbedford** [comment]
Your solution is much better if we can make it work.

**Comment by dschwen** [comment]
With

`cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_OPENMP=OFF -DWRAP_PYTHON=OFF . && make` 

how do I even test this? For the record it builds just fine on mac.

**Comment by dschwen** [comment]
is there a preprocessor symbol that I can use with `#ifdef` to compile conditionally depending on whether python is on or off?

**Comment by reverendbedford** [comment]
I was playing around with that last night.  Feel free to add one (in the main CMakeLists.txt).  Currently we have:

```
### PYTHON BINDINGS ###
option(WRAP_PYTHON "Generate a pybind11 wrapper" OFF)
if (WRAP_PYTHON)
      INCLUDE_DIRECTORIES(SYSTEM pybind11)
endif()
```

you could make that

```
### PYTHON BINDINGS ###
option(WRAP_PYTHON "Generate a pybind11 wrapper" OFF)
if (WRAP_PYTHON)
      add_definitions(-DWRAP_PYTHON)
      INCLUDE_DIRECTORIES(SYSTEM pybind11)
endif()
```

or similar.

The problem I was having is that people may want to link against a compiled version of lib/libneml.so without also linking the python stuff.  So the use case is you compile NEML with the bindings (to test or play with models) and then link the compiled libneml.so to your FEA code.  Right now you can link to libneml.so without the python library even if you compiled the bindings.  I couldn't get that to continue to work even with a preprocessor macro.

**Comment by reverendbedford** [comment]
I missed the earlier comment on testing.  The easiest way is to 

`cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_OPENMP=OFF -DWRAP_PYTHON=OFF -DBUILD_UTILS=ON . && make`

That will build some simple c/cxx/fortran wrappers that get deposited in util/*

You can automatically run some testing through this interface by running the "time_all.sh" script in the profiling directory.

Later today I'll add in some automatic testing without the bindings...

**Comment by dschwen** [comment]
Hm, if I turn off the python bindings `./time_all.sh` just immediately fails with `ImportError: cannot import name 'models' from 'neml' (/Users/schwd/Programs/neml/neml/__init__.py)`

**Comment by reverendbedford** [comment]
Sorry, that's the "check_memory.sh" script in that same directory, not the profiling script.  I'll expand our testing after I finish up something this afternoon.

**Comment by reverendbedford** [comment]
@dschwen sorry to cycle you, but I've the notification red :)  The tests suite now covers gcc{6,7,8} and tests both with the bindings and no bindings versions of the library.

**Comment by dschwen** [comment]
No, that's great. Better test coverage helps!

**Pull request closed without merging**
